// pages/api/admin/timeline/export.pdf.js
// Production-grade compliance timeline PDF export

import PDFDocument from "pdfkit";
import { sql } from "../../../../lib/db";

// Severity color mapping
const SEVERITY_COLORS = {
  critical: "#dc2626",
  high: "#ea580c",
  warning: "#ca8a04",
  info: "#2563eb",
  default: "#6b7280",
};

function getSeverityColor(severity) {
  return SEVERITY_COLORS[severity?.toLowerCase()] || SEVERITY_COLORS.default;
}

function formatDate(date) {
  if (!date) return "-";
  const d = new Date(date);
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatEventType(action) {
  if (!action) return "-";
  return action.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export default async function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).send("GET only");
  }

  try {
    const orgId = Number(req.query.orgId);

    // HARD GUARD — return empty PDF if no valid orgId
    if (!Number.isInteger(orgId) || orgId <= 0) {
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", "attachment; filename=compliance_report.pdf");
      const doc = new PDFDocument({ margin: 50 });
      doc.pipe(res);
      doc.fontSize(14).text("Invalid organization. Please try again.", 50, 50);
      doc.end();
      return;
    }

    // Get organization name
    const [org] = await sql`
      SELECT name FROM orgs WHERE id = ${orgId} LIMIT 1;
    `;
    const orgName = org?.name || `Organization #${orgId}`;

    // Get timeline events with vendor names
    const rows = await sql`
      SELECT
        t.created_at,
        t.action,
        t.severity,
        t.message,
        t.vendor_id,
        v.name AS vendor_name
      FROM vendor_timeline t
      LEFT JOIN vendors v ON v.id = t.vendor_id
      WHERE v.org_id = ${orgId}
      ORDER BY t.created_at DESC
      LIMIT 500;
    `;

    // Get summary stats
    const stats = {
      total: rows.length,
      critical: rows.filter((r) => r.severity === "critical").length,
      warning: rows.filter((r) => r.severity === "warning").length,
      info: rows.filter((r) => r.severity === "info").length,
    };

    // Setup PDF
    const filename = `compliance_report_${new Date().toISOString().split("T")[0]}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=${filename}`);

    const doc = new PDFDocument({
      margin: 50,
      size: "LETTER",
      info: {
        Title: "Compliance Timeline Report",
        Author: "Verivo Compliance Platform",
        Subject: `Compliance events for ${orgName}`,
        CreationDate: new Date(),
      },
    });
    doc.pipe(res);

    let pageNumber = 1;

    // Helper to add page footer
    const addFooter = () => {
      doc
        .fontSize(8)
        .fillColor("#9ca3af")
        .text(
          `Generated by Verivo | ${new Date().toLocaleString()} | Page ${pageNumber}`,
          50,
          doc.page.height - 40,
          { align: "center", width: doc.page.width - 100 }
        );
    };

    // ========== HEADER ==========
    doc
      .fontSize(24)
      .fillColor("#1e293b")
      .text("Compliance Timeline Report", { align: "center" })
      .moveDown(0.3);

    doc
      .fontSize(12)
      .fillColor("#64748b")
      .text(orgName, { align: "center" })
      .moveDown(0.3);

    doc
      .fontSize(10)
      .fillColor("#94a3b8")
      .text(`Generated: ${new Date().toLocaleString()}`, { align: "center" })
      .moveDown(1);

    // ========== SUMMARY BOX ==========
    const summaryY = doc.y;
    doc
      .rect(50, summaryY, doc.page.width - 100, 60)
      .fillAndStroke("#f8fafc", "#e2e8f0");

    doc
      .fontSize(10)
      .fillColor("#475569")
      .text("SUMMARY", 60, summaryY + 10);

    doc
      .fontSize(20)
      .fillColor("#1e293b")
      .text(String(stats.total), 60, summaryY + 28)
      .fontSize(9)
      .fillColor("#64748b")
      .text("Total Events", 60, summaryY + 48);

    doc
      .fontSize(20)
      .fillColor(SEVERITY_COLORS.critical)
      .text(String(stats.critical), 160, summaryY + 28)
      .fontSize(9)
      .fillColor("#64748b")
      .text("Critical", 160, summaryY + 48);

    doc
      .fontSize(20)
      .fillColor(SEVERITY_COLORS.warning)
      .text(String(stats.warning), 240, summaryY + 28)
      .fontSize(9)
      .fillColor("#64748b")
      .text("Warnings", 240, summaryY + 48);

    doc
      .fontSize(20)
      .fillColor(SEVERITY_COLORS.info)
      .text(String(stats.info), 320, summaryY + 28)
      .fontSize(9)
      .fillColor("#64748b")
      .text("Info", 320, summaryY + 48);

    doc.y = summaryY + 80;

    // ========== TABLE HEADER ==========
    if (!rows || rows.length === 0) {
      doc
        .fontSize(12)
        .fillColor("#64748b")
        .text("No compliance events found for this organization.", { align: "center" });
      addFooter();
      doc.end();
      return;
    }

    doc.moveDown(0.5);

    // Column positions
    const cols = {
      date: 50,
      event: 145,
      vendor: 280,
      message: 380,
    };

    const drawTableHeader = () => {
      const headerY = doc.y;
      doc
        .rect(50, headerY, doc.page.width - 100, 20)
        .fill("#1e293b");

      doc
        .fontSize(9)
        .fillColor("#ffffff")
        .text("DATE", cols.date + 5, headerY + 6)
        .text("EVENT", cols.event + 5, headerY + 6)
        .text("VENDOR", cols.vendor + 5, headerY + 6)
        .text("DETAILS", cols.message + 5, headerY + 6);

      doc.y = headerY + 25;
    };

    drawTableHeader();

    // ========== TABLE ROWS ==========
    for (let i = 0; i < rows.length; i++) {
      const r = rows[i];
      const rowY = doc.y;

      // Check for page break
      if (rowY > doc.page.height - 80) {
        addFooter();
        doc.addPage();
        pageNumber++;
        doc.y = 50;
        drawTableHeader();
      }

      // Alternating row background
      if (i % 2 === 0) {
        doc
          .rect(50, doc.y - 2, doc.page.width - 100, 18)
          .fill("#f8fafc");
      }

      const y = doc.y;

      // Severity indicator dot
      doc
        .circle(cols.date + 3, y + 5, 3)
        .fill(getSeverityColor(r.severity));

      // Date
      doc
        .fontSize(8)
        .fillColor("#475569")
        .text(formatDate(r.created_at), cols.date + 10, y, { width: 85 });

      // Event type
      doc
        .fontSize(8)
        .fillColor("#1e293b")
        .text(formatEventType(r.action), cols.event + 5, y, { width: 130 });

      // Vendor name
      doc
        .fontSize(8)
        .fillColor("#475569")
        .text(r.vendor_name || "-", cols.vendor + 5, y, { width: 95 });

      // Message (truncated)
      const message = r.message || "-";
      const truncatedMessage = message.length > 40 ? message.substring(0, 37) + "..." : message;
      doc
        .fontSize(8)
        .fillColor("#64748b")
        .text(truncatedMessage, cols.message + 5, y, { width: 150 });

      doc.y = y + 18;
    }

    // ========== FOOTER ==========
    addFooter();

    doc.end();
  } catch (err) {
    console.error("[timeline/export.pdf] error:", err);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=compliance_report_error.pdf");
    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);
    doc
      .fontSize(14)
      .fillColor("#dc2626")
      .text("Error generating report", 50, 50)
      .fontSize(10)
      .fillColor("#64748b")
      .text("Please try again or contact support.", 50, 70);
    doc.end();
  }
}

